// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: proto/roomInventory/rooms.proto

package roomInventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoomInventoryClient is the client API for RoomInventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomInventoryClient interface {
	NewRoom(ctx context.Context, in *RoomWithUserToken, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveRoom(ctx context.Context, in *RoomNumberWithUserToken, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type roomInventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomInventoryClient(cc grpc.ClientConnInterface) RoomInventoryClient {
	return &roomInventoryClient{cc}
}

func (c *roomInventoryClient) NewRoom(ctx context.Context, in *RoomWithUserToken, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/bookingSystem.proto.roomInventory.roomInventory/NewRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomInventoryClient) RemoveRoom(ctx context.Context, in *RoomNumberWithUserToken, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/bookingSystem.proto.roomInventory.roomInventory/removeRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomInventoryServer is the server API for RoomInventory service.
// All implementations must embed UnimplementedRoomInventoryServer
// for forward compatibility
type RoomInventoryServer interface {
	NewRoom(context.Context, *RoomWithUserToken) (*emptypb.Empty, error)
	RemoveRoom(context.Context, *RoomNumberWithUserToken) (*emptypb.Empty, error)
	mustEmbedUnimplementedRoomInventoryServer()
}

// UnimplementedRoomInventoryServer must be embedded to have forward compatible implementations.
type UnimplementedRoomInventoryServer struct {
}

func (UnimplementedRoomInventoryServer) NewRoom(context.Context, *RoomWithUserToken) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewRoom not implemented")
}
func (UnimplementedRoomInventoryServer) RemoveRoom(context.Context, *RoomNumberWithUserToken) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRoom not implemented")
}
func (UnimplementedRoomInventoryServer) mustEmbedUnimplementedRoomInventoryServer() {}

// UnsafeRoomInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomInventoryServer will
// result in compilation errors.
type UnsafeRoomInventoryServer interface {
	mustEmbedUnimplementedRoomInventoryServer()
}

func RegisterRoomInventoryServer(s grpc.ServiceRegistrar, srv RoomInventoryServer) {
	s.RegisterService(&RoomInventory_ServiceDesc, srv)
}

func _RoomInventory_NewRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomWithUserToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomInventoryServer).NewRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookingSystem.proto.roomInventory.roomInventory/NewRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomInventoryServer).NewRoom(ctx, req.(*RoomWithUserToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomInventory_RemoveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomNumberWithUserToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomInventoryServer).RemoveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookingSystem.proto.roomInventory.roomInventory/removeRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomInventoryServer).RemoveRoom(ctx, req.(*RoomNumberWithUserToken))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomInventory_ServiceDesc is the grpc.ServiceDesc for RoomInventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomInventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bookingSystem.proto.roomInventory.roomInventory",
	HandlerType: (*RoomInventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewRoom",
			Handler:    _RoomInventory_NewRoom_Handler,
		},
		{
			MethodName: "removeRoom",
			Handler:    _RoomInventory_RemoveRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/roomInventory/rooms.proto",
}
